### ISSUE TITLE
[Enhancement] Type definition to work with TypeScript.

### ISSUE THREAD

**Issue by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [the729/go-libra#12]
Is there a possible way to implement the type definition of gopherjs-libra to work with typescript?
I see such `.d.ts` generator `dts-gen` from microsoft can help to generate d.ts file from node or js library.

There is the generated d.ts file from gopherjs-libra.js.

```typescript
 /** Declaration file generated by dts-gen */

export = gopherjs_libra;

declare const gopherjs_libra: {
    libra: {
        accountReceivedEventPath: any;
        accountResourcePath: any;
        accountSentEventPath: any;
        client: any;
        inferProgramName: any;
        pubkeyToAddress: any;
        resourcePath: any;
    };
};
```

However, the origin javascript file need to be a module (translate to ts file) or exported. I'm trying to implement that at this time.

**Comment by the729** [comment]
It will be great to have gopherjs-libra work with typescript. I have little experience with js and even less with ts. To be honest I had spent several days to figure out how to make gopherjs transpiled code to work with both browsers and nodejs. 

You can rebuild the js file using gopherjs without -m option, so that it will not be minimized. I guess this will help you figure out how gopherjs organize the output js code.

Good luck!

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
> It will be great to have gopherjs-libra work with typescript. I have little experience with js and even less with ts. To be honest I had spent several days to figure out how to make gopherjs transpiled code to work with both browsers and nodejs.
> 
> You can rebuild the js file using gopherjs without -m option, so that it will not be minimized. I guess this will help you figure out how gopherjs organize the output js code.
> 
> Good luck!

It compatible with vue.js but react or react-js...

**Comment by the729** [comment]
I'm not expert in js or ts. So I can't help you with this issue. Pull requests are welcome if anyone has figured out how to make it work with ts.
